---
- name: add virtualhost for application
  template:
    src: apache-rails-application.j2
    dest: "/confs/{{web_server_name}}/{{vhost_shortname}}.conf"
  notify:
    - restart httpd
- name: start httpd
  service: name=httpd state=started enabled=yes
